// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWNh6L98Y1LdhI7BjkBAOryrXaOZx-TMU',
    appId: '1:408453139120:web:9cc31b260eea2f81200975',
    messagingSenderId: '408453139120',
    projectId: 'emailauth-ac84e',
    authDomain: 'emailauth-ac84e.firebaseapp.com',
    storageBucket: 'emailauth-ac84e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXk-ULoIv5GCZYSU37N_UhjKUrWkv55g',
    appId: '1:408453139120:android:d99fc70c46ca506a200975',
    messagingSenderId: '408453139120',
    projectId: 'emailauth-ac84e',
    storageBucket: 'emailauth-ac84e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6IKwLusJFSeBEWfmUQjGfgMxN7U2_Klw',
    appId: '1:408453139120:ios:386da651fb1438b7200975',
    messagingSenderId: '408453139120',
    projectId: 'emailauth-ac84e',
    storageBucket: 'emailauth-ac84e.appspot.com',
    iosBundleId: 'com.example.firbaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6IKwLusJFSeBEWfmUQjGfgMxN7U2_Klw',
    appId: '1:408453139120:ios:386da651fb1438b7200975',
    messagingSenderId: '408453139120',
    projectId: 'emailauth-ac84e',
    storageBucket: 'emailauth-ac84e.appspot.com',
    iosBundleId: 'com.example.firbaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWNh6L98Y1LdhI7BjkBAOryrXaOZx-TMU',
    appId: '1:408453139120:web:64232c7ef0a2a61d200975',
    messagingSenderId: '408453139120',
    projectId: 'emailauth-ac84e',
    authDomain: 'emailauth-ac84e.firebaseapp.com',
    storageBucket: 'emailauth-ac84e.appspot.com',
  );
}
